# Generated by Django 3.2.8 on 2021-11-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='sold2',
        ),
    ]
